name: server-tests

on:
  pull_request:
    paths: 
      - 'server/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm cd server && npm install && npm run test:ci